install_epel:                  true
install_webmin:                false
install_hyperv:                true
install_cockpit:               true
install_docker_workaround:     false
install_kubernetes_workaround: false
install_neofetch:              true
install_updates:               true
install_extra_groups:          true
docker_prepare:                false
extra_device:                  ""
install_motd:                  true
