variables:
  packer_version: "1.10.3"
  install_packer: "true"
  build_alma8: "false"
  build_alma9: "false"
  build_rocky8: "false"
  build_rocky9: "false"
  build_oracle8: "false"
  build_oracle9: "false"
  build_ubuntu2004: "false"
  build_ubuntu2204: "false"
  build_ubuntu2404: "false"
  build_windows2022_std: "false"
  build_windows2022_dc: "false"
  build_windows2019_std: "false"
  build_windows2019_dc: "false"
default:
  artifacts:
    expire_in: 4 hour
    when: always
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - script_failure
stages:
  - validate
  - install_packer
  - build
  - alma_build
  - rocky_build
  - oracle_build
  - windows_build
  - ubuntu_build

.validate:
  stage: validate
  variables:
    ACTION: verify
    LOG: 0
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="d:\packer_cache"'
    - packer init config.pkr.hcl
    - .\hv_generic.ps1 -Action $ACTION -Version $VERSION -Template $TEMPLATE -Log $LOG
  tags:
    - windows
    - hyperv

.build:
  stage: build
  variables:
    ACTION: build
    LOG: 0
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="d:\packer_cache"'
    - packer init config.pkr.hcl
    - Get-VM -Name packer-* | Remove-VM -Force -Verbose -ErrorAction SilentlyContinue;$true
    - .\hv_generic.ps1 -Action $ACTION -Version $VERSION -Template $TEMPLATE -Log $LOG
  tags:
    - windows
    - hyperv
  resource_group: build

alma8:
  variables:
    VERSION: almalinux-8.9
    TEMPLATE: rhel
  extends: .validate

alma9:
  variables:
    VERSION: almalinux-9.4
    TEMPLATE: rhel
  extends: .validate

rocky8:
  variables:
    VERSION: rockylinux-8.9
    TEMPLATE: rhel
  extends: .validate

rocky9:
  variables:
    VERSION: rockylinux-9.4
    TEMPLATE: rhel
  extends: .validate

oracle8:
  variables:
    VERSION: oraclelinux-8.9
    TEMPLATE: rhel
  extends: .validate

oracle9:
  variables:
    VERSION: oraclelinux-9.4
    TEMPLATE: rhel
  extends: .validate

windows2022std:
  variables:
    VERSION: windows_server_2022_std
    TEMPLATE: windows
  extends: .validate

windows2022dc:
  variables:
    VERSION: windows_server_2022_dc
    TEMPLATE: windows
  extends: .validate

windows2019std:
  variables:
    VERSION: windows_server_2019_std
    TEMPLATE: windows
  extends: .validate

windows2019dc:
  variables:
    VERSION: windows_server_2019_dc
    TEMPLATE: windows
  extends: .validate

ubuntu2004:
  variables:
    VERSION: ubuntu-20.04
    TEMPLATE: ubuntu
  extends: .validate

ubuntu2204:
  variables:
    VERSION: ubuntu-22.04
    TEMPLATE: ubuntu
  extends: .validate

ubuntu2404:
  variables:
    VERSION: ubuntu-24.04
    TEMPLATE: ubuntu
  extends: .validate


# Here building starts
# Install required packer choco package
install_packer:
  variables:
    GIT_STRATEGY: none
  stage: install_packer
  before_script:
    - pwd
    - echo $CI_COMMIT_BRANCH
    - '$env:PACKER_CACHE_DIR="d:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force -TurnOff -Verbose"
    - Sleep 30
    - "Get-Vm -name packer-*|Remove-VM -Force"
  script:
    - choco upgrade packer --version $packer_version -y
    - packer --version
  tags:
    - windows
    - hyperv
  rules:
    - if: $CI_COMMIT_BRANCH == "build" || $install_packer == "true"
      when: always

alma8_build:
  stage: alma_build
  variables:
    VERSION: almalinux-8.9
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_alma8 == "true"'
      when: always
  extends: .build

alma9_build:
  stage: alma_build
  variables:
    VERSION: almalinux-9.4
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_alma9 == "true"'
      when: always
  extends: .build

rocky8_build:
  stage: rocky_build
  variables:
    VERSION: rockylinux-8.9
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_rocky8 == "true"'
      when: always
  extends: .build

rocky9_build:
  stage: rocky_build
  variables:
    VERSION: rockylinux-9.4
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_rocky9 == "true"'
      when: always
  extends: .build

oracle8_build:
  stage: oracle_build
  variables:
    VERSION: oraclelinux-8.9
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_oracle8 == "true"'
      when: always
  extends: .build

oracle9_build:
  stage: oracle_build
  variables:
    VERSION: oraclelinux-9.4
    TEMPLATE: rhel
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_oracle9 == "true"'
      when: always
  extends: .build

windows2022_std_build:
  stage: windows_build
  variables:
    VERSION: windows_server_2022_std
    TEMPLATE: windows
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_windows2022_std == "true"'
      when: always
  extends: .build

windows2022_dc_build:
  stage: windows_build
  variables:
    VERSION: windows_server_2022_dc
    TEMPLATE: windows
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_windows2022_dc == "true"'
      when: always
  extends: .build

windows2019_std_build:
  stage: windows_build
  variables:
    VERSION: windows_server_2019_std
    TEMPLATE: windows
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_windows2019_std == "true"'
      when: always
  extends: .build

windows2019_dc_build:
  stage: windows_build
  variables:
    VERSION: windows_server_2019_dc
    TEMPLATE: windows
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_windows2019_dc == "true"'
      when: always
  extends: .build

ubuntu2004_build:
  stage: ubuntu_build
  variables:
    VERSION: ubuntu-20.04
    TEMPLATE: ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_ubuntu2004 == "true"'
      when: always
  extends: .build

ubuntu2204_build:
  stage: ubuntu_build
  variables:
    VERSION: ubuntu-22.04
    TEMPLATE: ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_ubuntu2204 == "true"'
      when: always
  extends: .build

ubuntu2404_build:
  stage: ubuntu_build
  variables:
    VERSION: ubuntu-24.04
    TEMPLATE: ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH == "build" || $build_ubuntu2404 == "true"'
      when: always
  extends: .build
